/*
 * File: app/view/WizMainTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Wiztalk.view.WizMainTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'container',
                itemId: 'kbContainer',
                style: 'background: #000024',
                layout: {
                    type: 'vbox'
                },
                title: 'Keyboard',
                iconCls: 'compose',
                items: [
                    {
                        xtype: 'container',
                        html: '',
                        itemId: 'kbTopRowContainer',
                        flex: 1.2,
                        items: [
                            {
                                xtype: 'label',
                                html: '+972 (52) 456-6440',
                                itemId: 'phoneNumLabel',
                                margin: 5,
                                styleHtmlContent: true
                            },
                            {
                                xtype: 'container',
                                itemId: 'infoContainer',
                                items: [
                                    {
                                        xtype: 'label',
                                        html: 'No information',
                                        itemId: 'kbInfoLabel',
                                        styleHtmlContent: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        html: '',
                        itemId: 'kbGridContainer',
                        layout: {
                            type: 'vbox'
                        },
                        flex: 4,
                        items: [
                            {
                                xtype: 'container',
                                itemId: 'kbRowA123',
                                layout: {
                                    type: 'hbox'
                                },
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'button',
                                        html: '1<br><font size="2%">&nbsp;</font>',
                                        itemId: 'kbButton1',
                                        style: '',
                                        styleHtmlContent: true,
                                        iconMask: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        cls: '',
                                        html: '2<br><font size="2%">ABC</font>',
                                        itemId: 'kbButton2',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '3<br><font size="2%">DEF</font>',
                                        itemId: 'kbButton3',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'kbRowB456',
                                layout: {
                                    type: 'hbox'
                                },
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'button',
                                        html: '4<br><font size="2%">GHI</font>',
                                        itemId: 'kbButton4',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '5<br><font size="2%">JKL</font>',
                                        itemId: 'kbButton5',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '6<br><font size="2%">MNO</font>',
                                        itemId: 'kbButton6',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'kbRowC789',
                                layout: {
                                    type: 'hbox'
                                },
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'button',
                                        html: '7<br><font size="2%">PQRS</font>',
                                        itemId: 'kbButton7',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '8<br><font size="2%">TUV </font>',
                                        itemId: 'kbButton8',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '9<br><font size="2%">WXYZ</font>',
                                        itemId: 'kbButton9',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'kbRowDstr0pnd',
                                layout: {
                                    type: 'hbox'
                                },
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'button',
                                        html: '<font size="6%">*</font><br><font size="2%"> </font>',
                                        itemId: 'kbButtonStar',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '0<br><font size="2%">+</font>',
                                        itemId: 'kbButton0',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '#<br><font size="2%">&nbsp;</font>',
                                        itemId: 'kbButtonHash',
                                        styleHtmlContent: true,
                                        text: '',
                                        flex: 1
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'kbRowEsend',
                                layout: {
                                    type: 'hbox'
                                },
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'button',
                                        html: '<font size="2%">Compare</font>',
                                        itemId: 'kbButtonCompareOrAddContact',
                                        ui: 'decline',
                                        text: 'Compare',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: '<font size="2%">Send</font>',
                                        itemId: 'kbButtonSend',
                                        ui: 'confirm',
                                        text: 'Send',
                                        flex: 1
                                    },
                                    {
                                        xtype: 'button',
                                        html: 'X',
                                        itemId: 'kbButtonDel',
                                        ui: 'decline',
                                        iconMask: true,
                                        text: '',
                                        flex: 1
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                itemId: 'contactsTabContainer',
                title: 'Contacts',
                iconCls: 'team',
                items: [
                    {
                        xtype: 'container',
                        itemId: 'contactsContainer',
                        style: '',
                        title: 'Contacts',
                        items: [
                            {
                                xtype: 'navigationview'
                            },
                            {
                                xtype: 'container',
                                itemId: 'newContactContainer'
                            },
                            {
                                xtype: 'list',
                                itemId: 'contactsList',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ],
                                store: 'contactsStore',
                                grouped: true,
                                onItemDisclosure: true,
                                plugins: [
                                    {
                                        autoPaging: true,
                                        type: 'listpaging'
                                    }
                                ],
                                indexBar: {
                                    itemId: 'contactsIndexBar'
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'favoritesContainer',
                        title: 'Favorites'
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'lastCallsContainer',
                title: 'Last calls',
                iconCls: 'time'
            },
            {
                xtype: 'container',
                itemId: 'reportsContainer',
                title: 'Reports',
                iconCls: 'favorites'
            },
            {
                xtype: 'container',
                itemId: 'moreContainer',
                title: 'More',
                iconCls: 'more'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});