/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    requires: [
        'Wiztalk.store.override.ContactsStore',
        'Wiztalk.controller.override.KbController'
    ],

    models: [
        'Contact'
    ],
    stores: [
        'ContactsStore'
    ],
    views: [
        'WizMainTabPanel'
    ],
    icon: 'PhoneIco.png',
    name: 'Wiztalk',
    controllers: [
        'KbController'
    ],

    launch: function() {
        console.log("App launched. Next line should work ok");
        //console.log("Sencha with PhoneGap on an " + navigator.platform);

        Ext.create('Wiztalk.view.WizMainTabPanel', {fullscreen: true});
    }

});
