/*
 * File: app/controller/KbController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Wiztalk.controller.KbController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.kbController',
    config: {
        control: {
            "#kbButton1": {
                tap: 'onKbButton1Tap'
            },
            "#kbButton3": {
                tap: 'onKbButton3Tap'
            },
            "#kbButton0": {
                tap: 'onKbButton0Tap'
            },
            "#kbButton4": {
                tap: 'onKbButton4Tap'
            },
            "#kbButton2": {
                tap: 'onKbButton2Tap'
            }
        }
    },

    onKbButton1Tap: function(button, e, options) {
        // fill this in intellij moshezzz
        console.log("single contact");
        //displayASingleContact();



    },

    onKbButton3Tap: function(button, e, options) {
        console.log("beep beep");
        navigator.notification.beep(2);
        console.log("after beep");

    },

    onKbButton0Tap: function(button, e, options) {
        console.log("addPhoneDigit 0");
        //addPhoneDigit('0');

    },

    onKbButton4Tap: function(button, e, options) {

    },

    onKbButton2Tap: function(button, e, options) {

    }

});